
; Generated by SpritePad - Subchrist Software, 2003-2022.
; Assemble with 64TASS or similar.


; Colour values...

COLR_VIC_SCREEN = 0
COLR_VIC_SPRITE_MC1 = 0
COLR_VIC_SPRITE_MC2 = 1


; Quantities and dimensions...

SPRITE_COUNT = 1


; Data block sizes (in bytes)...

SZ_SPRITESET_DATA = 64
SZ_SPRITESET_ATTRIB_DATA = 1


; Data block addresses (dummy values)...

addr_spriteset_data = $1000
addr_spriteset_attrib_data = $1000




; * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




; SpriteSet Data...
; 1 images, 64 bytes per image, total size is 64 ($40) bytes.

* = addr_spriteset_data
spriteset_data

sprite_image_0
.byte $00,$0C,$00,$00,$1E,$00,$00,$63,$80,$00,$98,$C0,$01,$0E,$60,$7C
.byte $01,$E0,$83,$F8,$20,$40,$07,$20,$43,$00,$E0,$24,$0C,$18,$08,$43
.byte $04,$08,$E0,$82,$09,$F8,$01,$09,$5E,$C2,$05,$5E,$D4,$03,$FF,$C0
.byte $03,$F7,$80,$03,$8F,$00,$01,$FC,$00,$00,$70,$00,$00,$00,$00,$01



; SpriteSet Attribute Data...
; 1 attributes, 1 per image, 8 bits each, total size is 1 ($1) bytes.
; nb. Upper nybbles = MYXV, lower nybbles = colour (0-15).

* = addr_spriteset_attrib_data
spriteset_attrib_data

.byte $01



